# Generated by Django 6.0.3 on 2026-04-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
