# Generated by Django 4.2.29 on 2026-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id_assignment', models.CharField(db_column='ID_assignment', max_length=10, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(blank=True, db_column='Assigned_at', null=True)),
            ],
            options={
                'db_table': 'assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id_campaign', models.CharField(db_column='ID_campaign', max_length=10, primary_key=True, serialize=False)),
                ('nama_camp', models.CharField(db_column='Nama_camp', max_length=100)),
                ('source', models.CharField(blank=True, db_column='Source', max_length=100, null=True)),
                ('production_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start_date', null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignLeads',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=10, primary_key=True, serialize=False)),
                ('funnel_position', models.CharField(blank=True, db_column='Funnel_position', max_length=50, null=True)),
                ('source', models.CharField(blank=True, db_column='Source', max_length=100, null=True)),
            ],
            options={
                'db_table': 'campaign_leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomFields',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=10, primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, db_column='Field_name', max_length=100, null=True)),
                ('value', models.TextField(blank=True, db_column='Value', null=True)),
            ],
            options={
                'db_table': 'custom_fields',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id_lead', models.CharField(db_column='ID_lead', max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(db_column='Nama', max_length=100)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('no_whatsapp', models.CharField(blank=True, db_column='no_Whatsapp', max_length=20, null=True)),
            ],
            options={
                'db_table': 'leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadsTag',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'leads_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginLogs',
            fields=[
                ('id_log', models.CharField(db_column='ID_log', max_length=10, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(blank=True, db_column='Login_time', null=True)),
            ],
            options={
                'db_table': 'login_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationLinks',
            fields=[
                ('id_link', models.CharField(db_column='Id_link', max_length=10, primary_key=True, serialize=False)),
                ('link_token', models.CharField(db_column='Link_token', max_length=255, unique=True)),
                ('generated_time', models.DateTimeField(blank=True, db_column='Generated_time', null=True)),
                ('expired_time', models.DateTimeField(blank=True, db_column='Expired_time', null=True)),
            ],
            options={
                'db_table': 'registration_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Segmentasi',
            fields=[
                ('id_seg', models.CharField(db_column='Id_seg', max_length=10, primary_key=True, serialize=False)),
                ('seg_name', models.CharField(db_column='Seg_name', max_length=100)),
            ],
            options={
                'db_table': 'segmentasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SegRule',
            fields=[
                ('id_rule', models.CharField(db_column='Id_rule', max_length=10, primary_key=True, serialize=False)),
                ('field', models.CharField(blank=True, db_column='Field', max_length=100, null=True)),
                ('logic', models.CharField(blank=True, db_column='Logic', max_length=20, null=True)),
            ],
            options={
                'db_table': 'seg_rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.CharField(db_column='Id_tag', max_length=10, primary_key=True, serialize=False)),
                ('label_tag', models.CharField(db_column='Label_tag', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.CharField(db_column='ID_user', max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(db_column='Nama', max_length=100)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('role', models.JSONField(blank=True, db_column='Role', null=True)),
                ('asal_perusahaan', models.CharField(db_column='Asal_perusahaan', max_length=100)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
