# Generated by Django 4.2.29 on 2026-06-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_assignment_campaign_campaignleads_customfields_leads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomColumn',
            fields=[
                ('id_col', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('col_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('dropdown', 'Dropdown')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('col_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'custom_column',
                'ordering': ['col_order', 'created_at'],
            },
        ),
    ]
